// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDndWOcuXpynvn_QWEUucfZZ6yZbYy8D_s',
    appId: '1:937682686639:web:f262f8514a48f49a0a3a5a',
    messagingSenderId: '937682686639',
    projectId: 'e-chiffa-67701',
    authDomain: 'e-chiffa-67701.firebaseapp.com',
    storageBucket: 'e-chiffa-67701.firebasestorage.app',
    measurementId: 'G-XWTVY00KXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATSedVsSWY_iF1JRSX4_9xY5TeShLqeSw',
    appId: '1:937682686639:android:413b051095a0546d0a3a5a',
    messagingSenderId: '937682686639',
    projectId: 'e-chiffa-67701',
    storageBucket: 'e-chiffa-67701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7PeXDfh91l63UtB5Spl8Tla5f6AmjfXw',
    appId: '1:937682686639:ios:782395c68d7e938d0a3a5a',
    messagingSenderId: '937682686639',
    projectId: 'e-chiffa-67701',
    storageBucket: 'e-chiffa-67701.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7PeXDfh91l63UtB5Spl8Tla5f6AmjfXw',
    appId: '1:937682686639:ios:782395c68d7e938d0a3a5a',
    messagingSenderId: '937682686639',
    projectId: 'e-chiffa-67701',
    storageBucket: 'e-chiffa-67701.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDndWOcuXpynvn_QWEUucfZZ6yZbYy8D_s',
    appId: '1:937682686639:web:415c73b53b2d17020a3a5a',
    messagingSenderId: '937682686639',
    projectId: 'e-chiffa-67701',
    authDomain: 'e-chiffa-67701.firebaseapp.com',
    storageBucket: 'e-chiffa-67701.firebasestorage.app',
    measurementId: 'G-F96F5YEPHC',
  );
}
